// Generated by CoffeeScript 1.6.3
(function() {
  window.ZVG = {};

  ZVG.BackgroundGradient = (function() {
    function BackgroundGradient(svg) {
      this.gradient = svg.append('defs').append('linearGradient').attr('x1', '0%').attr('y1', '0%').attr('x2', '80%').attr('y2', '50%').attr('spreadMethod', 'pad').attr('id', 'standardBackgroundGradient');
      this.gradient.append('stop').attr('offset', '10%').attr('stop-color', '#aaa').attr('stop-opacity', 1);
      this.gradient.append('stop').attr('offset', '110%').attr('stop-color', '#777').attr('stop-opacity', 1);
    }

    return BackgroundGradient;

  })();

  ZVG.Background = (function() {
    function Background(svg, height, width) {
      var backgrounGroup;
      ZVG.BackgroundGradient(svg);
      backgrounGroup = svg.append('g');
      backgrounGroup.append('rect').style('fill', 'url(#standardBackgroundGradient)').attr('height', height).attr('width', width).attr('rx', 5).attr('ry', 5);
    }

    return Background;

  })();

}).call(this);
