// Generated by CoffeeScript 1.6.2
(function() {
  window.ZVG = {
    flatUIColors: {
      'TURQUOISE': '#1ABC9C',
      'GREEN SEA': '#16A085',
      'EMERALD': '#2ECC71',
      'NEPHRITIS': '#27AE60',
      'PETER RIVER': '#3498DB',
      'BELIZE HOLE': '#2980B9',
      'AMETHYST': '#9B59B6',
      'WISTERIA': '#8E44AD',
      'WET ASPHALT': '#34495E',
      'MIDNIGHT BLUE': '#2C3E50',
      'SUN FLOWER': '#F1C40F',
      'ORANGE': '#F39C12',
      'CARROT': '#E67E22',
      'PUMPKIN': '#D35400',
      'ALIZARIN': '#E74C3C',
      'POMEGRANATE': '#C0392B',
      'CLOUDS': '#ECF0F1',
      'SILVER': '#BDC3C7',
      'CONCRETE': '#95A5A6',
      'ASBESTOS': '#7F8C8D'
    }
  };

  ZVG.BackgroundGradient = (function() {
    function BackgroundGradient(svg) {
      this.gradient = svg.append('defs').append('linearGradient').attr('x1', '0%').attr('y1', '0%').attr('x2', '80%').attr('y2', '50%').attr('spreadMethod', 'pad').attr('id', 'standardBackgroundGradient');
      this.gradient.append('stop').attr('offset', '10%').attr('stop-color', '#aaa').attr('stop-opacity', 1);
      this.gradient.append('stop').attr('offset', '110%').attr('stop-color', '#777').attr('stop-opacity', 1);
    }

    return BackgroundGradient;

  })();

  ZVG.Background = (function() {
    function Background(svg, height, width, radius) {
      var backgroundGroup;

      if (radius == null) {
        radius = 5;
      }
      ZVG.BackgroundGradient(svg);
      backgroundGroup = svg.append('g');
      this.background = backgroundGroup.append('rect').attr('fill', ZVG.flatUIColors['CLOUDS']).attr('height', height).attr('width', width).attr('rx', radius).attr('ry', radius);
    }

    return Background;

  })();

  ZVG.BasicChart = (function() {
    function BasicChart() {}

    BasicChart.prototype.width = 900;

    BasicChart.prototype.height = 500;

    BasicChart.prototype.data = function(d) {
      if (d) {
        this.raw_data = d;
        this._data = this.nestData(d);
        return this;
      }
      return this._data;
    };

    BasicChart.prototype.nestData = function(d) {
      return d3.nest().key(function(z) {
        return z.series_1;
      }).key(function(z) {
        return z.series_2;
      }).entries(d);
    };

    BasicChart.prototype.series_1_domain = function(d) {
      if (d) {
        this._series_1_domain = d;
        return this;
      }
      return this._series_1_domain;
    };

    BasicChart.prototype.series_2_domain = function(d) {
      if (d) {
        this._series_2_domain = d;
        return this;
      }
      return this._series_2_domain;
    };

    BasicChart.prototype.initializeSvg = function() {
      this.svg = d3.select('body').append('svg').attr('height', this.height + 200).attr('width', this.width + 200);
      return this.background = (new ZVG.Background(this.svg, this.height, this.width)).background;
    };

    return BasicChart;

  })();

}).call(this);
